name: CI-CD ETL Pipeline via Jenkins

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Trigger Jenkins Job
      run: |
        curl -X POST "${{ secrets.JENKINS_URL }}/job/etl-devops-pipeline/build" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"

    - name: Slack Notification on Success
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"✅ Jenkins job triggered successfully for branch *${{ github.ref }}*"}' \
        "${{ secrets.SLACK_WEBHOOK_URL }}"

    - name: Slack Notification on Failure
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"❌ Jenkins job failed for branch *${{ github.ref }}* at commit *${{ github.sha }}*"}' \
        "${{ secrets.SLACK_WEBHOOK_URL }}"

    - name: Send Email on Failure
      if: failure()
      run: |
        curl -X POST https://api.sendgrid.com/v3/mail/send \
        -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{
          "personalizations": [{
            "to": [{"email": "${{ secrets.ALERT_EMAIL }}"}],
            "subject": "❌ Jenkins Job Failed - GitHub Actions",
            "dynamic_template_data": {}
          }],
          "from": {"email": "noreply@yourdomain.com"},
          "content": [{
            "type": "text/plain",
            "value": "GitHub Actions failed triggering Jenkins job.\nBranch: ${{ github.ref }}\nCommit: ${{ github.sha }}\nCheck: https://github.com/${{ github.repository }}/actions"
          }]
        }'
